name: d5y-cloud
services:
  app:
    image: ${APP_OWNER}/${APP_NAME}:${APP_VERSION}
    restart: unless-stopped
    pull_policy: always
    ports:
      - 127.0.0.1:${HTTP_PORT}:9000
    environment:
      APP_SERVER_ADDR: :9000
      APP_WEATHER_APIKEY: ${APP_WEATHER_APIKEY}
      APP_GITHUB_TOKEN: ${APP_GITHUB_TOKEN}
