on:
  - push
  - workflow_dispatch

jobs:
  lint:
    uses: ashep/ci/.github/workflows/go-lint.yaml@v1

  test:
    uses: ashep/ci/.github/workflows/go-test.yaml@v1

  build:
    needs:
      - test
      - lint
    uses: ashep/ci/.github/workflows/go-build.yaml@v1
    with:
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  deploy:
    uses: ashep/ci/.github/workflows/deploy-docker.yaml@v1
    needs:
      - build
    with:
      ssh_host: ${{ vars.DEPLOY_SSH_HOST }}
      ssh_port: ${{ vars.DEPLOY_SSH_PORT }}
      ssh_user: ${{ vars.DEPLOY_SSH_USER }}
    secrets:
      ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
      dotenv: |
        HTTP_PORT=${{ vars.DEPLOY_HTTP_PORT }}
        APP_WEATHER_APIKEY=${{ secrets.WEATHER_APIKEY }}
        APP_GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
